### PR TITLE
adding hypsp

### PR DESCRIPTION
**Pull request by MarconiS**
adding hyperspectral 50x50 tiles

### CODE REVIEW

**Comment by bw4sz** [comment]
I think we need to make it exactly the same extent to be sensible in this repo. Is that difficult?

**Comment by MarconiS** [comment]
not at all; I just have to reduce the buffer around the plot center. 40 by 40 it is then! :)

**Comment by bw4sz** [comment]
@MarconiS when you get back, let me know when this is resolved. Preferably the lidar CHM * the hyperspec, matching the extent of the polygons of the tower plots. I got the maintainers of the rectlabel tool to add a "show depth channel"

https://github.com/ryouchinsa/Rectlabel-support/issues/107

so we can change the file names and use them in rectlabel. If this is too much work, let me know and I'll do it. I'm done NIWO.

**Comment by bw4sz** [comment]
Also, just trying out one of these files. It can't be opened by preview. Something about the encoding you used in saving the .tif. I get "The file “4142000_MLBS_008.tif could not be opened.It may be damaged or use a file format that Preview doesn’t recognize."

**Comment by bw4sz** [comment]
Nevermind, I can now see that these are the 370 band rasters, no the 3 channel false colors. We probably need both eventually. I'm labeling some MLBS right now and playing with the false colors, but i don't know the index numbers? 

```
library(raster)
s<-stack("/Users/Ben/Downloads/4136000_MLBS_063.tif")
> nlayers(s)
[1] 370
> names(s)
  [1] "X4136000_MLBS_063.1"   "X4136000_MLBS_063.2"   "X4136000_MLBS_063.3"  
  [4] "X4136000_MLBS_063.4"   "X4136000_MLBS_063.5"   "X4136000_MLBS_063.6"  
  [7] "X4136000_MLBS_063.7"   "X4136000_MLBS_063.8"   "X4136000_MLBS_063.9"  
 [10] "X4136000_MLBS_063.10"  "X4136000_MLBS_063.11"  "X4136000_MLBS_063.12" 
```

looking for these guys  (R = 829 nm, G = 473 nm, B = 669 nm)

**Pull request closed without merging**
